Description: CodeBuild to build Cloud Website
version: 0.2

environment_variables:
  plaintext:
    "Building Cloud Website": ""

phases:
  pre_build:
    commands:
      - echo "Cloning _repo_name_ repo"
      - script_directory=$(pwd)
      - echo $script_directory
      # - python "folder/file.py" "Secrets_Manager_Id_Containing_Developer_Token" "Github_Repo_Name"
      - python PythonFiles/clone_git_repo.py cloud_website_developer_token _repo_name_
      
  build:
    commands:
      - echo "Creating Cloud Website Container Image"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123412341234.dkr.ecr.us-east-1.amazonaws.com
      - cd ..
      - cd ..
      - cd /tmp
      - cd _repo_name_/
      - timestamp=$(date "+%d%m%Y%H%M%S")
      - echo $timestamp
      - docker build -t cloud_website:$timestamp .
      - docker tag cloud_website:$timestamp 123412341234.dkr.ecr.us-east-1.amazonaws.com/cloud_website:$timestamp
      - docker push 123412341234.dkr.ecr.us-east-1.amazonaws.com/cloud_website:$timestamp

  post_build:
    commands:
      - echo "Update ECS Service to Consume New Image"
      - cd ..
      - cd ..
      - cd $script_directory
      - python PythonFiles/update_ecs.py
