# This is a basic workflow that is automated triggered

name: Automated Triggered by Git Pull/Push/Merge

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, Linux ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out code
      uses: actions/checkout@v2
        
  # Runs a single command using the runners shell
    - name: Run a one-line script
      run: /usr/local/bin/aws --version

  # Federate Credentials for Temporary Programmatic Access
    - uses: _enterprise_/AWS-Federation-Action@v3
      with:
#         awsaccount: "1234"
#         awsrole: "CloudEngineer"
#         sid: ${{secrets.UN}}
#         password: ${{secrets.PW}}
          awsaccount: "1234"
          awsrole: "CloudDeveloper"
#           awsrole: "CloudEngineer"
          sid: ${{secrets.username_dev}}
          password: ${{secrets.password_dev}}

#     # Deploy Cloudformation
#     - name: Deploy Cloudformation
#       uses: aws-actions/aws-cloudformation-github-deploy@master
#       with:
#         name: myteststack-s3-bucket
#         template: cloudformation/_cloudformation_s3_bucket_asdf.yml
#         no-fail-on-empty-changeset: "1"
# #         parameter-overrides: >-
# #           AvailabilityZones=${{ github.event.inputs.region }}a,
# #           AvailabilityZones=${{ github.event.inputs.region }}c,

#     - name: Use output       
#       run: |          
#        /usr/local/bin/aws s3 ls     

#   # Install npm
#     - name: install npm
#       run: 'sudo apt update -y && sudo apt install nodejs npm -y'
  
#   # Install AWS CDK
#     - name: Install AWS CDK
#       run: 'sudo npm install -g aws-cdk'
  
#   # Install Requirements
#     - name: Install Requirements
#       run: 'pip3 install -r requirements.txt'
# #       working-directory: CDK-AWS
  
#   # CDK Synth
#     - name: CDK Synth
#       run: cdk synth
# #       working-directory: CDK-AWS

##################################################################################################
  # Run Execute Cloudformation Script (./script stack_name region template/location)
    - name: Create/Update Cloudformation Stack
      shell: bash
      run: | 
        ./execute_cloudformation.sh myteststack-8910 us-east-1 cloudformation/_cloudformation_s3_bucket_asdf.yml
#   # Run Execute Cloudformation Script (./script stack_name region template/location)
#     - name: Create/Update Cloudformation Stack
#       shell: bash
#       run: | 
#         ./execute_cloudformation.sh myteststack-123 us-east-1 cloudformation/_cloudformation_CustomResource_I_Did_Something.yml
##################################################################################################      

#   # Run Execute Cloudformation Script (./script stack_name region template/location)
#     - name: Create/Update Cloudformation Stack
#       shell: bash
#       run: | 
#         ./execute_cloudformation.sh myteststack-s3-bucket us-east-1 cloudformation/_cloudformation_s3_bucket.yml
