Description: Deploys CustomResource that will return the SecurityGroupId of a specified SecurityGroupName.  This CustomResource
             can be used to programmatically retrieve the dynamically created SecurityGroups in any account.
             Example Usage -
              # Resources:
              # rGetSecurityGroup:
              #   Type: Custom::GetSecurityGroup
              #   Properties:
              #     ServiceToken: !Sub "arn:aws:lambda:us-east-1:${AWS::AccountId}:function:lambda_CustomResource_Get_SecurityGroup"
              #     SecurityGroup: securityGroupName123
              
              # rLambda:
              #   DependsOn: rGetSecurityGroup
              #   Type: AWS::Lambda::Function
              #   Properties: 
              #     Handler: "lambda.lambda_handler"
              #     Role: !GetAtt rIamRole.Arn
              #     Code: 
              #       ZipFile: |
              #           # Import Modules
              #           import boto3
              #           import logging
              #     Runtime: python3.7
              #     VpcConfig: 
              #       SubnetIds: 
              #         - subnet-123
              #         - subnet-456
              #         - subnet-789
              #       SecurityGroupIds:
              #         - Fn::GetAtt: 
              #           - rGetSecurityGroup
              #           - security_group_found

Parameters:
  S3ObjectVersion:
    Description: The Version ID of the s3 object.  Used for programmatically identifying code changes.
    Type: String
Resources:
#create lambda no tags function
  AWSGetSecurityGroupsLambda:
    Type: AWS::Lambda::Function
    Properties: 
      Code:
        S3Bucket: "s3BucketName"
        S3Key: "shared/lambda/functions/lambda_CustomResource_Get_SecurityGroup.zip"
        S3ObjectVersion: !Ref S3ObjectVersion
      Description: "CustomResource that returns the SecurityGroupId of a specified SecurityGroupName for a calling Cloudformation Template"
      FunctionName: "lambda_CustomResource_Get_SecurityGroup"
      Handler: "lambda_CustomResource_Get_SecurityGroup.lambda_handler"
      MemorySize: 128
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/CloudLambda"
      Runtime: "python3.8"
      Timeout: 60
      Tags:
        -
          Key: "ProductName"
          Value: "value0"
        -
          Key: "Owner"
          Value: "value1"
        -
          Key: "Team"
          Value: "value2"
        -
          Key: "BusinessUnit"
          Value: "value3"
